# supporting backends for node-appoptics testing
#
# requires copying ../oboe-test/collectors/<collector-name>/<name>.crt
# to test/certs/<collector-name>.crt
#
version: '2.1'
services:
  web-aaa:
    ports:
      - "8088:8088"
    environment:
      - TODO_SERVER_OPTIONS=${TODO_SERVER_OPTIONS}
    build:
      context: .
      args:
        - TODO_SERVICE_KEY=${AO_TOKEN_STG}:web-aaa
        # expect librato/node-appoptics-bindings#new-liboboe while private
        #- AO_TEST_PACKAGE=${AO_TEST_PACKAGE}
        # expect a git auth token (or extend Dockerfile with user and password)
        #- AO_TEST_GITAUTH=${AO_TEST_GITAUTH}
        # - AO_TEST_GITUSER
        # - AO_TEST_GITPASS

        # scribe collector
        # - AO_TEST_COLLECTOR=${AO_COLLECTOR:-scribe-collector:4444}
        # - AO_TEST_COLLECTOR_CERT=${AO_COLLECTOR_CERT:-test/certs/scribe-collector.crt}

        # java collector
        # - AO_TEST_COLLECTOR=${AO_COLLECTOR:-java-collector:12222}
        # - AO_TEST_COLLECTOR_CERT=${AO_COLLECTOR_CERT:-test/certs/java-collector.crt}

        # staging collector - depends on $AO_TOKEN_STG being valid
        - APPOPTICS_COLLECTOR=collector-stg.appoptics.com
        - APPOPTICS_REPORTER=ssl

        # set the backend (mongodb) address to use
        - TODO_MONGODB_ADDRESS=mongo_2_4:27017
        #
        # Rebuild starting with fetching the todo application
        #
        - TODO_REFETCH
        # and reinstall the application
        - TODO_REINSTALL
    image: todo-web-aaa
    #volumes:
      # map the directory this file is in to the todo directory
      # - "${PWD}:/home/node/todo/"
    logging:
      options:
        max-file: "1"
        max-size: 50m

  web-bbb:
    expose:
      - "8088"
    environment:
      - TODO_SERVER_OPTIONS=${TODO_SERVER_OPTIONS}
    build:
      context: .
      args:
        - TODO_SERVICE_KEY=${AO_TOKEN_STG}:web-bbb
        - APPOPTICS_COLLECTOR=collector-stg.appoptics.com
        - APPOPTICS_REPORTER=ssl

        # set the backend (mongodb) address to use
        - TODO_MONGODB_ADDRESS=mongo_2_4:27017
        - TODO_REFETCH
        - TODO_REINSTALL
    image: todo-web-bbb
    #volumes:
      # map the directory this file is in to the todo directory
      # - "${PWD}:/home/node/todo/"
    logging:
      options:
        max-file: "1"
        max-size: 50m

  web-ccc:
    expose:
      - "8088"
    environment:
      - TODO_SERVER_OPTIONS=${TODO_SERVER_OPTIONS}
    build:
      context: .
      args:
        - TODO_SERVICE_KEY=${AO_TOKEN_STG}:web-ccc
        - APPOPTICS_COLLECTOR=collector-stg.appoptics.com
        - APPOPTICS_REPORTER=ssl

        # set the backend (mongodb) address to use
        - TODO_MONGODB_ADDRESS=mongo_2_4:27017

        - TODO_REFETCH
        - TODO_REINSTALL
    image: todo-web-ccc
    #volumes:
      # map the directory this file is in to the todo directory
      # - "${PWD}:/home/node/todo/"
    logging:
      options:
        max-file: "1"
        max-size: 50m

  mongo_2_4:
    image: "mongo_2_4"
    build:
      context: test/docker/
      dockerfile: mongo_2_4.yml
    logging:
      options:
        max-file: "1"
        max-size: 50m
    ports:
      # host:container (avoid conflict with ao test host port)
      - "27027:27017"
